name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Great! Your submission will now go under some manual and automated verifications. We will let you know if any action is required from your side.'
